name: my_CI_workflow

on:
  [pull_request]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name : Run unit test
        run: python3 -m unittest
  
